# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrets',
            name='secret',
            field=models.TextField(default=None),
        ),
    ]
